---
  title: "Problem Set 1"
output: pdf_document
---
  
  ```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Grade: 20/20
Good job!

# Overview
Learning how to use git and GitHub can be intimidating. Problem sets this quarter will give you the opportunity to practice using git and GitHub both individually and in groups. In this problem set we are asking you to create a folder and file using your command line interface (Git Bash or terminal). These files you create on your local computer will later be pushed into a remote repository you create. These exercises will give you practice with the git/GitHub workflow (e.g. changing directories, creating files, staging those files, committing, and pushing to GitHub). Lastly, you will practice creating issues on our **rclass2** repository. We will be using the **issues** page in the **rclass** repository to ask questions.    

# Part I: Command line & R practice (7/7) 

1. Using your command line interface (CLI) (e.g. Git Bash, terminal), create a new folder called **scripts**. Change directories to where you want to save this folder. Be intentional about where you create this folder (hint: change directories first). Write the commands you used here (to change directories and create the folder):  
  
  ```
#Change Directory
cd /c/Users/gfunkscholar/desktop/UCLA/Spring_2020/EDUC_263

#Create Folder
mkdir scripts

```  

2. Change directory into the **scripts** folder and write the command you used here:  
  
  ```
#Change directory to **scripts**
cd scripts
```

3. Inside the **scripts** folder, create a file called `problemset1.R` via the command line. Write the command you used here:  
  
  ```
#Created file within **scripts** folder
touch problemset1.R

```

4. Open `problemset1.R` in RStudio to edit the file and perform the following tasks:
  
  - Load the `tidyverse` library

- Preview the first 5 rows of the `mpg` dataframe  

- Filter the `mpg` dataframe to include only Ford Mustang's that were built after the year 2000


# Part II: GitHub (10/10) 

1. Log in to your GitHub account online and create a new private repository here: https://github.com/organizations/Rucla-ed/repositories/new 

    Name it **lastname_ps1** and do not forget to initialize it with a `README.md` file. Paste the link to your repository here:
```
https://github.com/Rucla-ed/Reyes_ps1

```

2. Clone the **lastname_ps1** repository to your local machine (again be intentional about where you save this folder): 

    Write the git command you used here:  

```
cd /Users/gfunkscholar/desktop/UCLA/Spring_2020/EDUC_263/rclass2
git clone https://github.com/Rucla-ed/Reyes_ps1.git

```

3. Change directory into **lastname_ps1**. Write the command you used here:  

```
cd /Users/gfunkscholar/desktop/UCLA/Spring_2020/EDUC_263/rclass2/Reyes_ps1
```

4. What is the command to list all the directory contents in **lastname_ps1**, including hidden files and directories (ie. entries starting with `.`)?  

#This command is **ls -a**


```
    Write the command you used here and paste your output:
.		..		.DS_Store	.git		Reyes_ps1
```


5. Since **lastname_ps1** is a git repository, you can run git commands in this directory. What is the command to check the current state of the repository?  

    Write the git command you used here and paste your output:

```
#Commands
git init /Users/gfunkscholar/Desktop/UCLA/Spring_2020/EDUC_263/rclass2/Reyes_ps1
git status

#Output
On branch master

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.DS_Store
	Reyes_ps1/

nothing added to commit but untracked files present (use "git add" to track)
```


6. Go back to the folder **scripts** you created in Part I and move this folder inside your **lastname_ps1** folder on your local machine. Now check the status of your repository (what you did in the question above). 

    Write the git command you used here and paste your output: 

```
#Command
git status

#Output
On branch master

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.DS_Store
	Reyes_ps1/


```

7. Add the new folder and file you've created (`scripts/problemset1.R`) to the staging area. Write the git command you used here:  
  
  ```
git add /Users/gfunkscholar/desktop/UCLA/Spring_2020/EDUC_263/rclass2/Reyes_ps1/scripts/problemset1.R
```

8. Commit your changes with a message of your choice and write the git command you used here:  
  
NOTICE THAT YOU NEED TO CONFIGURE YOUR GITHUB. YOU COULD DO IT BY TYPING THE FOLLOWING COMMANDS ON YOUR COMMAND LINE:
  
git config --global user.name "Your Name"
git config --global user.email you@example.com

  ```
#Command Used
git commit -m **Reyes_ps1** (File name is quoted in the code.)

[master b7b2cfe] Reyes_ps1 Commit
Committer: Bernard Reyes <gfunkscholar@Bernards-MacBook-Air.local>
  Your name and email address were configured automatically based
on your username and hostname. Please check that they are accurate.
You can suppress this message by setting them explicitly:
  
  git config --global user.name "Your Name"
git config --global user.email you@example.com

After doing this, you may fix the identity used for this commit with:
  
  git commit --amend --reset-author

1 file changed, 3 insertions(+)
create mode 100644 scripts/problemset1.R

```

9. Push your changes to the remote repository and write the git command you used here:  
  
  ```
"Command Used"
git push


```

10. Finally, add this file you are working on (`problemset1.Rmd`) to the **scripts** folder and push to the remote repository as well.



# Part III: GitHub issues (3/3) 

1. Navigate to the issues tab for the **rclass2** repository here: https://github.com/Rucla-ed/rclass2/issues

Create a new issue titled "Problem Set 1 - YOUR NAME" and post a question of your choice (e.g favorite food, self-care practices, favorite shows). Add the "question" label to your issue and assign it to 3 students in the class who you do not know.

Once your issue received 3 responses, close the issue. If other students assigned you to their issue, make sure to post your response as well. You should get an email notification if you were assigned to an issue.
